2023-12-31 15:52:21,830:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-12-31 15:52:21,831:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-12-31 15:52:21,831:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-12-31 15:52:21,831:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-12-31 15:52:23,513:INFO:PyCaret ClassificationExperiment
2023-12-31 15:52:23,513:INFO:Logging name: clf-default-name
2023-12-31 15:52:23,513:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-12-31 15:52:23,513:INFO:version 3.2.0
2023-12-31 15:52:23,513:INFO:Initializing setup()
2023-12-31 15:52:23,513:INFO:self.USI: 6a56
2023-12-31 15:52:23,514:INFO:self._variable_keys: {'is_multiclass', 'X_train', 'logging_param', 'USI', 'idx', 'y', 'y_test', 'seed', 'gpu_n_jobs_param', 'html_param', 'gpu_param', '_ml_usecase', '_available_plots', 'exp_id', 'target_param', 'fold_shuffle_param', 'exp_name_log', 'pipeline', 'log_plots_param', 'fold_groups_param', 'y_train', 'fold_generator', 'fix_imbalance', 'data', 'X_test', 'n_jobs_param', 'memory', 'X'}
2023-12-31 15:52:23,514:INFO:Checking environment
2023-12-31 15:52:23,514:INFO:python_version: 3.10.6
2023-12-31 15:52:23,514:INFO:python_build: ('tags/v3.10.6:9c7b4bd', 'Aug  1 2022 21:53:49')
2023-12-31 15:52:23,514:INFO:machine: AMD64
2023-12-31 15:52:23,514:INFO:platform: Windows-10-10.0.19045-SP0
2023-12-31 15:52:23,522:INFO:Memory: svmem(total=34260537344, available=14266548224, percent=58.4, used=19993989120, free=14266548224)
2023-12-31 15:52:23,522:INFO:Physical Core: 6
2023-12-31 15:52:23,522:INFO:Logical Core: 12
2023-12-31 15:52:23,523:INFO:Checking libraries
2023-12-31 15:52:23,523:INFO:System:
2023-12-31 15:52:23,523:INFO:    python: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
2023-12-31 15:52:23,523:INFO:executable: c:\Users\ttbon\Documents\cc_fraud_detection\.venv\Scripts\python.exe
2023-12-31 15:52:23,523:INFO:   machine: Windows-10-10.0.19045-SP0
2023-12-31 15:52:23,523:INFO:PyCaret required dependencies:
2023-12-31 15:52:23,559:INFO:                 pip: 22.2.1
2023-12-31 15:52:23,559:INFO:          setuptools: 63.2.0
2023-12-31 15:52:23,559:INFO:             pycaret: 3.2.0
2023-12-31 15:52:23,559:INFO:             IPython: 8.19.0
2023-12-31 15:52:23,559:INFO:          ipywidgets: 8.1.1
2023-12-31 15:52:23,559:INFO:                tqdm: 4.66.1
2023-12-31 15:52:23,559:INFO:               numpy: 1.25.2
2023-12-31 15:52:23,559:INFO:              pandas: 1.5.3
2023-12-31 15:52:23,559:INFO:              jinja2: 3.1.2
2023-12-31 15:52:23,559:INFO:               scipy: 1.10.1
2023-12-31 15:52:23,559:INFO:              joblib: 1.3.2
2023-12-31 15:52:23,559:INFO:             sklearn: 1.2.2
2023-12-31 15:52:23,559:INFO:                pyod: 1.1.2
2023-12-31 15:52:23,559:INFO:            imblearn: 0.11.0
2023-12-31 15:52:23,559:INFO:   category_encoders: 2.6.3
2023-12-31 15:52:23,559:INFO:            lightgbm: 4.2.0
2023-12-31 15:52:23,559:INFO:               numba: 0.58.1
2023-12-31 15:52:23,560:INFO:            requests: 2.31.0
2023-12-31 15:52:23,560:INFO:          matplotlib: 3.6.0
2023-12-31 15:52:23,560:INFO:          scikitplot: 0.3.7
2023-12-31 15:52:23,560:INFO:         yellowbrick: 1.5
2023-12-31 15:52:23,560:INFO:              plotly: 5.18.0
2023-12-31 15:52:23,560:INFO:    plotly-resampler: Not installed
2023-12-31 15:52:23,560:INFO:             kaleido: 0.2.1
2023-12-31 15:52:23,560:INFO:           schemdraw: 0.15
2023-12-31 15:52:23,560:INFO:         statsmodels: 0.14.1
2023-12-31 15:52:23,560:INFO:              sktime: 0.21.1
2023-12-31 15:52:23,560:INFO:               tbats: 1.1.3
2023-12-31 15:52:23,560:INFO:            pmdarima: 2.0.4
2023-12-31 15:52:23,560:INFO:              psutil: 5.9.7
2023-12-31 15:52:23,560:INFO:          markupsafe: 2.1.3
2023-12-31 15:52:23,560:INFO:             pickle5: Not installed
2023-12-31 15:52:23,560:INFO:         cloudpickle: 3.0.0
2023-12-31 15:52:23,560:INFO:         deprecation: 2.1.0
2023-12-31 15:52:23,560:INFO:              xxhash: 3.4.1
2023-12-31 15:52:23,560:INFO:           wurlitzer: Not installed
2023-12-31 15:52:23,560:INFO:PyCaret optional dependencies:
2023-12-31 15:52:23,577:INFO:                shap: Not installed
2023-12-31 15:52:23,577:INFO:           interpret: Not installed
2023-12-31 15:52:23,577:INFO:                umap: Not installed
2023-12-31 15:52:23,577:INFO:     ydata_profiling: Not installed
2023-12-31 15:52:23,577:INFO:  explainerdashboard: Not installed
2023-12-31 15:52:23,577:INFO:             autoviz: Not installed
2023-12-31 15:52:23,577:INFO:           fairlearn: Not installed
2023-12-31 15:52:23,577:INFO:          deepchecks: Not installed
2023-12-31 15:52:23,577:INFO:             xgboost: Not installed
2023-12-31 15:52:23,577:INFO:            catboost: Not installed
2023-12-31 15:52:23,577:INFO:              kmodes: Not installed
2023-12-31 15:52:23,578:INFO:             mlxtend: Not installed
2023-12-31 15:52:23,578:INFO:       statsforecast: Not installed
2023-12-31 15:52:23,578:INFO:        tune_sklearn: Not installed
2023-12-31 15:52:23,578:INFO:                 ray: Not installed
2023-12-31 15:52:23,578:INFO:            hyperopt: Not installed
2023-12-31 15:52:23,578:INFO:              optuna: Not installed
2023-12-31 15:52:23,578:INFO:               skopt: Not installed
2023-12-31 15:52:23,578:INFO:              mlflow: Not installed
2023-12-31 15:52:23,578:INFO:              gradio: Not installed
2023-12-31 15:52:23,578:INFO:             fastapi: Not installed
2023-12-31 15:52:23,578:INFO:             uvicorn: Not installed
2023-12-31 15:52:23,578:INFO:              m2cgen: Not installed
2023-12-31 15:52:23,578:INFO:           evidently: Not installed
2023-12-31 15:52:23,578:INFO:               fugue: Not installed
2023-12-31 15:52:23,578:INFO:           streamlit: Not installed
2023-12-31 15:52:23,578:INFO:             prophet: Not installed
2023-12-31 15:52:23,578:INFO:None
2023-12-31 15:52:23,578:INFO:Set up data.
2023-12-31 15:52:23,709:INFO:Set up folding strategy.
2023-12-31 15:52:23,709:INFO:Set up train/test split.
2023-12-31 15:52:23,902:INFO:Set up index.
2023-12-31 15:52:23,914:INFO:Assigning column types.
2023-12-31 15:52:24,013:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-12-31 15:52:24,047:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-12-31 15:52:24,051:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-12-31 15:52:24,088:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-31 15:52:24,089:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-31 15:52:24,122:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-12-31 15:52:24,123:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-12-31 15:52:24,143:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-31 15:52:24,143:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-31 15:52:24,143:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2023-12-31 15:52:24,174:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-12-31 15:52:24,193:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-31 15:52:24,193:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-31 15:52:24,225:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-12-31 15:52:24,247:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-31 15:52:24,248:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-31 15:52:24,248:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2023-12-31 15:52:24,304:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-31 15:52:24,304:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-31 15:52:24,359:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-31 15:52:24,359:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-31 15:52:24,365:INFO:Preparing preprocessing pipeline...
2023-12-31 15:52:24,377:INFO:Set up simple imputation.
2023-12-31 15:52:24,583:INFO:Finished creating preprocessing pipeline.
2023-12-31 15:52:24,589:INFO:Pipeline: Pipeline(memory=FastMemory(location=C:\Users\ttbon\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['Time', 'V1', 'V2', 'V3', 'V4',
                                             'V5', 'V6', 'V7', 'V8', 'V9',
                                             'V10', 'V11', 'V12', 'V13', 'V14',
                                             'V15', 'V16', 'V17', 'V18', 'V19',
                                             'V20', 'V21', 'V22', 'V23', 'V24',
                                             'V25', 'V26', 'V27', 'V28',
                                             'Amount'],
                                    transformer=SimpleImputer(a...
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='mean',
                                                              verbose='deprecated'))),
                ('categorical_imputer',
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated')))],
         verbose=False)
2023-12-31 15:52:24,589:INFO:Creating final display dataframe.
2023-12-31 15:52:25,170:INFO:Setup _display_container:                     Description             Value
0                    Session id              6242
1                        Target             Class
2                   Target type            Binary
3           Original data shape      (284807, 31)
4        Transformed data shape      (284807, 31)
5   Transformed train set shape      (199364, 31)
6    Transformed test set shape       (85443, 31)
7              Numeric features                30
8                    Preprocess              True
9               Imputation type            simple
10           Numeric imputation              mean
11       Categorical imputation              mode
12               Fold Generator   StratifiedKFold
13                  Fold Number                10
14                     CPU Jobs                -1
15                      Use GPU             False
16               Log Experiment             False
17              Experiment Name  clf-default-name
18                          USI              6a56
2023-12-31 15:52:25,234:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-31 15:52:25,234:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-31 15:52:25,287:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-31 15:52:25,288:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-31 15:52:25,288:INFO:setup() successfully completed in 1.78s...............
2023-12-31 15:52:25,289:INFO:Initializing compare_models()
2023-12-31 15:52:25,289:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001FD84FB2590>, include=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x000001FD84FB2590>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2023-12-31 15:52:25,289:INFO:Checking exceptions
2023-12-31 15:52:25,375:INFO:Preparing display monitor
2023-12-31 15:52:25,392:INFO:Initializing Logistic Regression
2023-12-31 15:52:25,392:INFO:Total runtime is 0.0 minutes
2023-12-31 15:52:25,394:INFO:SubProcess create_model() called ==================================
2023-12-31 15:52:25,394:INFO:Initializing create_model()
2023-12-31 15:52:25,394:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001FD84FB2590>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001FD87A3BA00>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-31 15:52:25,395:INFO:Checking exceptions
2023-12-31 15:52:25,395:INFO:Importing libraries
2023-12-31 15:52:25,395:INFO:Copying training dataset
2023-12-31 15:52:25,562:INFO:Defining folds
2023-12-31 15:52:25,562:INFO:Declaring metric variables
2023-12-31 15:52:25,565:INFO:Importing untrained model
2023-12-31 15:52:25,567:INFO:Logistic Regression Imported successfully
2023-12-31 15:52:25,572:INFO:Starting cross validation
2023-12-31 15:52:25,573:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-31 15:52:52,313:INFO:Calculating mean and std
2023-12-31 15:52:52,314:INFO:Creating metrics dataframe
2023-12-31 15:52:52,317:INFO:Uploading results into container
2023-12-31 15:52:52,317:INFO:Uploading model into container now
2023-12-31 15:52:52,318:INFO:_master_model_container: 1
2023-12-31 15:52:52,318:INFO:_display_container: 2
2023-12-31 15:52:52,318:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=6242, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-12-31 15:52:52,319:INFO:create_model() successfully completed......................................
2023-12-31 15:52:52,439:INFO:SubProcess create_model() end ==================================
2023-12-31 15:52:52,439:INFO:Creating metrics dataframe
2023-12-31 15:52:52,446:INFO:Initializing K Neighbors Classifier
2023-12-31 15:52:52,446:INFO:Total runtime is 0.4508979916572571 minutes
2023-12-31 15:52:52,448:INFO:SubProcess create_model() called ==================================
2023-12-31 15:52:52,448:INFO:Initializing create_model()
2023-12-31 15:52:52,448:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001FD84FB2590>, estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001FD87A3BA00>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-31 15:52:52,448:INFO:Checking exceptions
2023-12-31 15:52:52,448:INFO:Importing libraries
2023-12-31 15:52:52,449:INFO:Copying training dataset
2023-12-31 15:52:52,552:INFO:Defining folds
2023-12-31 15:52:52,553:INFO:Declaring metric variables
2023-12-31 15:52:52,556:INFO:Importing untrained model
2023-12-31 15:52:52,558:INFO:K Neighbors Classifier Imported successfully
2023-12-31 15:52:52,563:INFO:Starting cross validation
2023-12-31 15:52:52,563:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-31 15:53:47,055:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-31 15:53:47,074:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-31 15:53:49,281:INFO:Calculating mean and std
2023-12-31 15:53:49,283:INFO:Creating metrics dataframe
2023-12-31 15:53:49,285:INFO:Uploading results into container
2023-12-31 15:53:49,286:INFO:Uploading model into container now
2023-12-31 15:53:49,286:INFO:_master_model_container: 2
2023-12-31 15:53:49,286:INFO:_display_container: 2
2023-12-31 15:53:49,287:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2023-12-31 15:53:49,287:INFO:create_model() successfully completed......................................
2023-12-31 15:53:49,411:INFO:SubProcess create_model() end ==================================
2023-12-31 15:53:49,411:INFO:Creating metrics dataframe
2023-12-31 15:53:49,418:INFO:Initializing Naive Bayes
2023-12-31 15:53:49,418:INFO:Total runtime is 1.4004276394844055 minutes
2023-12-31 15:53:49,421:INFO:SubProcess create_model() called ==================================
2023-12-31 15:53:49,421:INFO:Initializing create_model()
2023-12-31 15:53:49,422:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001FD84FB2590>, estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001FD87A3BA00>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-31 15:53:49,422:INFO:Checking exceptions
2023-12-31 15:53:49,422:INFO:Importing libraries
2023-12-31 15:53:49,422:INFO:Copying training dataset
2023-12-31 15:53:49,530:INFO:Defining folds
2023-12-31 15:53:49,530:INFO:Declaring metric variables
2023-12-31 15:53:49,535:INFO:Importing untrained model
2023-12-31 15:53:49,537:INFO:Naive Bayes Imported successfully
2023-12-31 15:53:49,542:INFO:Starting cross validation
2023-12-31 15:53:49,543:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-31 15:53:50,564:INFO:Calculating mean and std
2023-12-31 15:53:50,565:INFO:Creating metrics dataframe
2023-12-31 15:53:50,569:INFO:Uploading results into container
2023-12-31 15:53:50,569:INFO:Uploading model into container now
2023-12-31 15:53:50,570:INFO:_master_model_container: 3
2023-12-31 15:53:50,570:INFO:_display_container: 2
2023-12-31 15:53:50,570:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-12-31 15:53:50,570:INFO:create_model() successfully completed......................................
2023-12-31 15:53:50,703:INFO:SubProcess create_model() end ==================================
2023-12-31 15:53:50,704:INFO:Creating metrics dataframe
2023-12-31 15:53:50,711:INFO:Initializing Decision Tree Classifier
2023-12-31 15:53:50,712:INFO:Total runtime is 1.4219937086105348 minutes
2023-12-31 15:53:50,714:INFO:SubProcess create_model() called ==================================
2023-12-31 15:53:50,715:INFO:Initializing create_model()
2023-12-31 15:53:50,715:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001FD84FB2590>, estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001FD87A3BA00>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-31 15:53:50,715:INFO:Checking exceptions
2023-12-31 15:53:50,715:INFO:Importing libraries
2023-12-31 15:53:50,715:INFO:Copying training dataset
2023-12-31 15:53:50,847:INFO:Defining folds
2023-12-31 15:53:50,848:INFO:Declaring metric variables
2023-12-31 15:53:50,851:INFO:Importing untrained model
2023-12-31 15:53:50,854:INFO:Decision Tree Classifier Imported successfully
2023-12-31 15:53:50,858:INFO:Starting cross validation
2023-12-31 15:53:50,859:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-31 15:54:08,801:INFO:Calculating mean and std
2023-12-31 15:54:08,803:INFO:Creating metrics dataframe
2023-12-31 15:54:08,807:INFO:Uploading results into container
2023-12-31 15:54:08,807:INFO:Uploading model into container now
2023-12-31 15:54:08,808:INFO:_master_model_container: 4
2023-12-31 15:54:08,808:INFO:_display_container: 2
2023-12-31 15:54:08,808:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=6242, splitter='best')
2023-12-31 15:54:08,808:INFO:create_model() successfully completed......................................
2023-12-31 15:54:08,921:INFO:SubProcess create_model() end ==================================
2023-12-31 15:54:08,921:INFO:Creating metrics dataframe
2023-12-31 15:54:08,928:INFO:Initializing SVM - Linear Kernel
2023-12-31 15:54:08,929:INFO:Total runtime is 1.7256096959114076 minutes
2023-12-31 15:54:08,931:INFO:SubProcess create_model() called ==================================
2023-12-31 15:54:08,931:INFO:Initializing create_model()
2023-12-31 15:54:08,932:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001FD84FB2590>, estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001FD87A3BA00>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-31 15:54:08,932:INFO:Checking exceptions
2023-12-31 15:54:08,932:INFO:Importing libraries
2023-12-31 15:54:08,932:INFO:Copying training dataset
2023-12-31 15:54:09,033:INFO:Defining folds
2023-12-31 15:54:09,033:INFO:Declaring metric variables
2023-12-31 15:54:09,036:INFO:Importing untrained model
2023-12-31 15:54:09,040:INFO:SVM - Linear Kernel Imported successfully
2023-12-31 15:54:09,045:INFO:Starting cross validation
2023-12-31 15:54:09,046:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-31 15:54:20,712:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-31 15:54:20,726:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-31 15:54:21,162:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-31 15:54:21,180:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-31 15:54:21,198:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-31 15:54:21,446:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-31 15:54:22,644:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-31 15:54:23,179:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-31 15:54:23,187:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-31 15:54:23,928:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-31 15:54:23,936:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-31 15:54:24,785:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-31 15:54:25,231:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-31 15:54:26,416:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-31 15:54:26,554:INFO:Calculating mean and std
2023-12-31 15:54:26,555:INFO:Creating metrics dataframe
2023-12-31 15:54:26,558:INFO:Uploading results into container
2023-12-31 15:54:26,558:INFO:Uploading model into container now
2023-12-31 15:54:26,559:INFO:_master_model_container: 5
2023-12-31 15:54:26,559:INFO:_display_container: 2
2023-12-31 15:54:26,559:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=6242, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-12-31 15:54:26,559:INFO:create_model() successfully completed......................................
2023-12-31 15:54:26,672:INFO:SubProcess create_model() end ==================================
2023-12-31 15:54:26,672:INFO:Creating metrics dataframe
2023-12-31 15:54:26,680:INFO:Initializing Ridge Classifier
2023-12-31 15:54:26,680:INFO:Total runtime is 2.0214672923088073 minutes
2023-12-31 15:54:26,683:INFO:SubProcess create_model() called ==================================
2023-12-31 15:54:26,683:INFO:Initializing create_model()
2023-12-31 15:54:26,684:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001FD84FB2590>, estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001FD87A3BA00>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-31 15:54:26,684:INFO:Checking exceptions
2023-12-31 15:54:26,684:INFO:Importing libraries
2023-12-31 15:54:26,684:INFO:Copying training dataset
2023-12-31 15:54:26,792:INFO:Defining folds
2023-12-31 15:54:26,792:INFO:Declaring metric variables
2023-12-31 15:54:26,795:INFO:Importing untrained model
2023-12-31 15:54:26,797:INFO:Ridge Classifier Imported successfully
2023-12-31 15:54:26,802:INFO:Starting cross validation
2023-12-31 15:54:26,802:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-31 15:54:27,457:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=2.58008e-11): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-12-31 15:54:27,459:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=2.56817e-11): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-12-31 15:54:27,461:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=2.59048e-11): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-12-31 15:54:27,472:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=2.49641e-11): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-12-31 15:54:27,485:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=2.55965e-11): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-12-31 15:54:27,485:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=2.60627e-11): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-12-31 15:54:27,496:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=2.46042e-11): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-12-31 15:54:27,504:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-31 15:54:27,512:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-31 15:54:27,527:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-31 15:54:27,527:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-31 15:54:27,528:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-31 15:54:27,546:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-31 15:54:27,565:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=2.52879e-11): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-12-31 15:54:27,569:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-31 15:54:27,570:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=2.46831e-11): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-12-31 15:54:27,590:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-31 15:54:27,590:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-31 15:54:27,592:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-31 15:54:27,726:INFO:Calculating mean and std
2023-12-31 15:54:27,727:INFO:Creating metrics dataframe
2023-12-31 15:54:27,729:INFO:Uploading results into container
2023-12-31 15:54:27,730:INFO:Uploading model into container now
2023-12-31 15:54:27,730:INFO:_master_model_container: 6
2023-12-31 15:54:27,730:INFO:_display_container: 2
2023-12-31 15:54:27,730:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=6242, solver='auto',
                tol=0.0001)
2023-12-31 15:54:27,731:INFO:create_model() successfully completed......................................
2023-12-31 15:54:27,857:INFO:SubProcess create_model() end ==================================
2023-12-31 15:54:27,857:INFO:Creating metrics dataframe
2023-12-31 15:54:27,865:INFO:Initializing Random Forest Classifier
2023-12-31 15:54:27,865:INFO:Total runtime is 2.0412147680918373 minutes
2023-12-31 15:54:27,868:INFO:SubProcess create_model() called ==================================
2023-12-31 15:54:27,868:INFO:Initializing create_model()
2023-12-31 15:54:27,868:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001FD84FB2590>, estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001FD87A3BA00>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-31 15:54:27,868:INFO:Checking exceptions
2023-12-31 15:54:27,869:INFO:Importing libraries
2023-12-31 15:54:27,869:INFO:Copying training dataset
2023-12-31 15:54:28,022:INFO:Defining folds
2023-12-31 15:54:28,022:INFO:Declaring metric variables
2023-12-31 15:54:28,026:INFO:Importing untrained model
2023-12-31 15:54:28,029:INFO:Random Forest Classifier Imported successfully
2023-12-31 15:54:28,033:INFO:Starting cross validation
2023-12-31 15:54:28,034:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-31 15:57:36,697:INFO:Calculating mean and std
2023-12-31 15:57:36,698:INFO:Creating metrics dataframe
2023-12-31 15:57:36,701:INFO:Uploading results into container
2023-12-31 15:57:36,702:INFO:Uploading model into container now
2023-12-31 15:57:36,702:INFO:_master_model_container: 7
2023-12-31 15:57:36,702:INFO:_display_container: 2
2023-12-31 15:57:36,703:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=6242, verbose=0, warm_start=False)
2023-12-31 15:57:36,703:INFO:create_model() successfully completed......................................
2023-12-31 15:57:36,819:INFO:SubProcess create_model() end ==================================
2023-12-31 15:57:36,819:INFO:Creating metrics dataframe
2023-12-31 15:57:36,827:INFO:Initializing Quadratic Discriminant Analysis
2023-12-31 15:57:36,827:INFO:Total runtime is 5.190571331977845 minutes
2023-12-31 15:57:36,830:INFO:SubProcess create_model() called ==================================
2023-12-31 15:57:36,830:INFO:Initializing create_model()
2023-12-31 15:57:36,830:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001FD84FB2590>, estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001FD87A3BA00>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-31 15:57:36,830:INFO:Checking exceptions
2023-12-31 15:57:36,830:INFO:Importing libraries
2023-12-31 15:57:36,831:INFO:Copying training dataset
2023-12-31 15:57:36,946:INFO:Defining folds
2023-12-31 15:57:36,947:INFO:Declaring metric variables
2023-12-31 15:57:36,950:INFO:Importing untrained model
2023-12-31 15:57:36,953:INFO:Quadratic Discriminant Analysis Imported successfully
2023-12-31 15:57:36,958:INFO:Starting cross validation
2023-12-31 15:57:36,959:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-31 15:57:40,305:INFO:Calculating mean and std
2023-12-31 15:57:40,306:INFO:Creating metrics dataframe
2023-12-31 15:57:40,309:INFO:Uploading results into container
2023-12-31 15:57:40,310:INFO:Uploading model into container now
2023-12-31 15:57:40,310:INFO:_master_model_container: 8
2023-12-31 15:57:40,310:INFO:_display_container: 2
2023-12-31 15:57:40,310:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2023-12-31 15:57:40,310:INFO:create_model() successfully completed......................................
2023-12-31 15:57:40,441:INFO:SubProcess create_model() end ==================================
2023-12-31 15:57:40,442:INFO:Creating metrics dataframe
2023-12-31 15:57:40,450:INFO:Initializing Ada Boost Classifier
2023-12-31 15:57:40,450:INFO:Total runtime is 5.2509604851404825 minutes
2023-12-31 15:57:40,452:INFO:SubProcess create_model() called ==================================
2023-12-31 15:57:40,452:INFO:Initializing create_model()
2023-12-31 15:57:40,452:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001FD84FB2590>, estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001FD87A3BA00>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-31 15:57:40,452:INFO:Checking exceptions
2023-12-31 15:57:40,452:INFO:Importing libraries
2023-12-31 15:57:40,452:INFO:Copying training dataset
2023-12-31 15:57:40,570:INFO:Defining folds
2023-12-31 15:57:40,570:INFO:Declaring metric variables
2023-12-31 15:57:40,573:INFO:Importing untrained model
2023-12-31 15:57:40,576:INFO:Ada Boost Classifier Imported successfully
2023-12-31 15:57:40,580:INFO:Starting cross validation
2023-12-31 15:57:40,581:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-31 15:58:45,945:INFO:Calculating mean and std
2023-12-31 15:58:45,947:INFO:Creating metrics dataframe
2023-12-31 15:58:45,949:INFO:Uploading results into container
2023-12-31 15:58:45,950:INFO:Uploading model into container now
2023-12-31 15:58:45,950:INFO:_master_model_container: 9
2023-12-31 15:58:45,950:INFO:_display_container: 2
2023-12-31 15:58:45,950:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=6242)
2023-12-31 15:58:45,950:INFO:create_model() successfully completed......................................
2023-12-31 15:58:46,060:INFO:SubProcess create_model() end ==================================
2023-12-31 15:58:46,060:INFO:Creating metrics dataframe
2023-12-31 15:58:46,069:INFO:Initializing Gradient Boosting Classifier
2023-12-31 15:58:46,069:INFO:Total runtime is 6.3446090857187905 minutes
2023-12-31 15:58:46,071:INFO:SubProcess create_model() called ==================================
2023-12-31 15:58:46,071:INFO:Initializing create_model()
2023-12-31 15:58:46,071:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001FD84FB2590>, estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001FD87A3BA00>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-31 15:58:46,071:INFO:Checking exceptions
2023-12-31 15:58:46,071:INFO:Importing libraries
2023-12-31 15:58:46,071:INFO:Copying training dataset
2023-12-31 15:58:46,169:INFO:Defining folds
2023-12-31 15:58:46,170:INFO:Declaring metric variables
2023-12-31 15:58:46,173:INFO:Importing untrained model
2023-12-31 15:58:46,175:INFO:Gradient Boosting Classifier Imported successfully
2023-12-31 15:58:46,180:INFO:Starting cross validation
2023-12-31 15:58:46,181:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-31 16:04:09,117:INFO:Calculating mean and std
2023-12-31 16:04:09,118:INFO:Creating metrics dataframe
2023-12-31 16:04:09,121:INFO:Uploading results into container
2023-12-31 16:04:09,121:INFO:Uploading model into container now
2023-12-31 16:04:09,122:INFO:_master_model_container: 10
2023-12-31 16:04:09,122:INFO:_display_container: 2
2023-12-31 16:04:09,122:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=6242, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-12-31 16:04:09,122:INFO:create_model() successfully completed......................................
2023-12-31 16:04:09,228:INFO:SubProcess create_model() end ==================================
2023-12-31 16:04:09,228:INFO:Creating metrics dataframe
2023-12-31 16:04:09,236:INFO:Initializing Linear Discriminant Analysis
2023-12-31 16:04:09,236:INFO:Total runtime is 11.73073714574178 minutes
2023-12-31 16:04:09,238:INFO:SubProcess create_model() called ==================================
2023-12-31 16:04:09,239:INFO:Initializing create_model()
2023-12-31 16:04:09,239:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001FD84FB2590>, estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001FD87A3BA00>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-31 16:04:09,239:INFO:Checking exceptions
2023-12-31 16:04:09,239:INFO:Importing libraries
2023-12-31 16:04:09,239:INFO:Copying training dataset
2023-12-31 16:04:09,351:INFO:Defining folds
2023-12-31 16:04:09,351:INFO:Declaring metric variables
2023-12-31 16:04:09,354:INFO:Importing untrained model
2023-12-31 16:04:09,357:INFO:Linear Discriminant Analysis Imported successfully
2023-12-31 16:04:09,362:INFO:Starting cross validation
2023-12-31 16:04:09,362:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-31 16:04:12,851:INFO:Calculating mean and std
2023-12-31 16:04:12,852:INFO:Creating metrics dataframe
2023-12-31 16:04:12,854:INFO:Uploading results into container
2023-12-31 16:04:12,855:INFO:Uploading model into container now
2023-12-31 16:04:12,855:INFO:_master_model_container: 11
2023-12-31 16:04:12,855:INFO:_display_container: 2
2023-12-31 16:04:12,855:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2023-12-31 16:04:12,855:INFO:create_model() successfully completed......................................
2023-12-31 16:04:12,974:INFO:SubProcess create_model() end ==================================
2023-12-31 16:04:12,974:INFO:Creating metrics dataframe
2023-12-31 16:04:12,982:INFO:Initializing Extra Trees Classifier
2023-12-31 16:04:12,983:INFO:Total runtime is 11.793184220790863 minutes
2023-12-31 16:04:12,985:INFO:SubProcess create_model() called ==================================
2023-12-31 16:04:12,985:INFO:Initializing create_model()
2023-12-31 16:04:12,985:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001FD84FB2590>, estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001FD87A3BA00>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-31 16:04:12,985:INFO:Checking exceptions
2023-12-31 16:04:12,985:INFO:Importing libraries
2023-12-31 16:04:12,985:INFO:Copying training dataset
2023-12-31 16:04:13,098:INFO:Defining folds
2023-12-31 16:04:13,098:INFO:Declaring metric variables
2023-12-31 16:04:13,101:INFO:Importing untrained model
2023-12-31 16:04:13,104:INFO:Extra Trees Classifier Imported successfully
2023-12-31 16:04:13,108:INFO:Starting cross validation
2023-12-31 16:04:13,109:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-31 16:04:42,804:INFO:Calculating mean and std
2023-12-31 16:04:42,805:INFO:Creating metrics dataframe
2023-12-31 16:04:42,807:INFO:Uploading results into container
2023-12-31 16:04:42,808:INFO:Uploading model into container now
2023-12-31 16:04:42,808:INFO:_master_model_container: 12
2023-12-31 16:04:42,808:INFO:_display_container: 2
2023-12-31 16:04:42,809:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=6242, verbose=0, warm_start=False)
2023-12-31 16:04:42,809:INFO:create_model() successfully completed......................................
2023-12-31 16:04:42,934:INFO:SubProcess create_model() end ==================================
2023-12-31 16:04:42,934:INFO:Creating metrics dataframe
2023-12-31 16:04:42,943:INFO:Initializing Light Gradient Boosting Machine
2023-12-31 16:04:42,943:INFO:Total runtime is 12.292515130837758 minutes
2023-12-31 16:04:42,946:INFO:SubProcess create_model() called ==================================
2023-12-31 16:04:42,946:INFO:Initializing create_model()
2023-12-31 16:04:42,946:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001FD84FB2590>, estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001FD87A3BA00>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-31 16:04:42,946:INFO:Checking exceptions
2023-12-31 16:04:42,947:INFO:Importing libraries
2023-12-31 16:04:42,947:INFO:Copying training dataset
2023-12-31 16:04:43,053:INFO:Defining folds
2023-12-31 16:04:43,054:INFO:Declaring metric variables
2023-12-31 16:04:43,057:INFO:Importing untrained model
2023-12-31 16:04:43,060:INFO:Light Gradient Boosting Machine Imported successfully
2023-12-31 16:04:43,066:INFO:Starting cross validation
2023-12-31 16:04:43,066:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-31 16:04:52,317:INFO:Calculating mean and std
2023-12-31 16:04:52,319:INFO:Creating metrics dataframe
2023-12-31 16:04:52,321:INFO:Uploading results into container
2023-12-31 16:04:52,322:INFO:Uploading model into container now
2023-12-31 16:04:52,322:INFO:_master_model_container: 13
2023-12-31 16:04:52,322:INFO:_display_container: 2
2023-12-31 16:04:52,322:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=6242, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2023-12-31 16:04:52,322:INFO:create_model() successfully completed......................................
2023-12-31 16:04:52,438:INFO:SubProcess create_model() end ==================================
2023-12-31 16:04:52,438:INFO:Creating metrics dataframe
2023-12-31 16:04:52,446:INFO:Initializing Dummy Classifier
2023-12-31 16:04:52,447:INFO:Total runtime is 12.450920987129212 minutes
2023-12-31 16:04:52,449:INFO:SubProcess create_model() called ==================================
2023-12-31 16:04:52,449:INFO:Initializing create_model()
2023-12-31 16:04:52,449:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001FD84FB2590>, estimator=dummy, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001FD87A3BA00>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-31 16:04:52,449:INFO:Checking exceptions
2023-12-31 16:04:52,449:INFO:Importing libraries
2023-12-31 16:04:52,449:INFO:Copying training dataset
2023-12-31 16:04:52,566:INFO:Defining folds
2023-12-31 16:04:52,566:INFO:Declaring metric variables
2023-12-31 16:04:52,569:INFO:Importing untrained model
2023-12-31 16:04:52,571:INFO:Dummy Classifier Imported successfully
2023-12-31 16:04:52,576:INFO:Starting cross validation
2023-12-31 16:04:52,576:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-31 16:04:52,960:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-31 16:04:52,966:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-31 16:04:52,971:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-31 16:04:52,973:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-31 16:04:52,983:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-31 16:04:52,990:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-31 16:04:53,005:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-31 16:04:53,010:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-31 16:04:53,023:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-31 16:04:53,043:WARNING:c:\Users\ttbon\Documents\cc_fraud_detection\.venv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-31 16:04:53,173:INFO:Calculating mean and std
2023-12-31 16:04:53,174:INFO:Creating metrics dataframe
2023-12-31 16:04:53,177:INFO:Uploading results into container
2023-12-31 16:04:53,177:INFO:Uploading model into container now
2023-12-31 16:04:53,178:INFO:_master_model_container: 14
2023-12-31 16:04:53,178:INFO:_display_container: 2
2023-12-31 16:04:53,178:INFO:DummyClassifier(constant=None, random_state=6242, strategy='prior')
2023-12-31 16:04:53,178:INFO:create_model() successfully completed......................................
2023-12-31 16:04:53,290:INFO:SubProcess create_model() end ==================================
2023-12-31 16:04:53,290:INFO:Creating metrics dataframe
2023-12-31 16:04:53,308:INFO:Initializing create_model()
2023-12-31 16:04:53,308:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001FD84FB2590>, estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=6242, verbose=0, warm_start=False), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-31 16:04:53,308:INFO:Checking exceptions
2023-12-31 16:04:53,310:INFO:Importing libraries
2023-12-31 16:04:53,310:INFO:Copying training dataset
2023-12-31 16:04:53,430:INFO:Defining folds
2023-12-31 16:04:53,431:INFO:Declaring metric variables
2023-12-31 16:04:53,431:INFO:Importing untrained model
2023-12-31 16:04:53,431:INFO:Declaring custom model
2023-12-31 16:04:53,432:INFO:Random Forest Classifier Imported successfully
2023-12-31 16:04:53,432:INFO:Cross validation set to False
2023-12-31 16:04:53,432:INFO:Fitting Model
2023-12-31 16:05:18,412:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=6242, verbose=0, warm_start=False)
2023-12-31 16:05:18,412:INFO:create_model() successfully completed......................................
2023-12-31 16:05:18,533:INFO:_master_model_container: 14
2023-12-31 16:05:18,533:INFO:_display_container: 2
2023-12-31 16:05:18,533:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=6242, verbose=0, warm_start=False)
2023-12-31 16:05:18,534:INFO:compare_models() successfully completed......................................
2023-12-31 16:05:18,534:INFO:Initializing create_model()
2023-12-31 16:05:18,534:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001FD84FB2590>, estimator=rf, fold=None, round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=True, system=True, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-31 16:05:18,534:INFO:Checking exceptions
2023-12-31 16:05:18,543:INFO:Importing libraries
2023-12-31 16:05:18,543:INFO:Copying training dataset
2023-12-31 16:05:18,659:INFO:Defining folds
2023-12-31 16:05:18,660:INFO:Declaring metric variables
2023-12-31 16:05:18,662:INFO:Importing untrained model
2023-12-31 16:05:18,665:INFO:Random Forest Classifier Imported successfully
2023-12-31 16:05:18,669:INFO:Starting cross validation
2023-12-31 16:05:18,669:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-31 16:08:19,388:INFO:Calculating mean and std
2023-12-31 16:08:19,390:INFO:Creating metrics dataframe
2023-12-31 16:08:19,395:INFO:Finalizing model
2023-12-31 16:08:44,478:INFO:Uploading results into container
2023-12-31 16:08:44,479:INFO:Uploading model into container now
2023-12-31 16:08:44,486:INFO:_master_model_container: 15
2023-12-31 16:08:44,486:INFO:_display_container: 3
2023-12-31 16:08:44,486:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=6242, verbose=0, warm_start=False)
2023-12-31 16:08:44,486:INFO:create_model() successfully completed......................................
2023-12-31 16:09:00,972:INFO:Initializing tune_model()
2023-12-31 16:09:00,972:INFO:tune_model(estimator=random_forest, fold=None, round=4, n_iter=10, custom_grid=None, optimize=Accuracy, custom_scorer=None, search_library=scikit-learn, search_algorithm=None, early_stopping=False, early_stopping_max_iters=10, choose_better=True, fit_kwargs=None, groups=None, return_tuner=False, verbose=True, tuner_verbose=True, return_train_score=False, kwargs={}, self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001FD84FB2590>)
2023-12-31 16:09:00,972:INFO:Checking exceptions
